services:
  apache1:
    image: httpd:latest
    container_name: apache1
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    networks:
      - f1_net

  apache2:
    image: httpd:latest
    container_name: apache2
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    networks:
      - f1_net

  nginx_proxy:
    image: nginx:latest
    container_name: nginx_balancer
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cache:/var/cache/nginx
    depends_on:
      - apache1
      - apache2
    networks:
      - f1_net

networks:
  f1_net:
    driver: bridge
