events { 
    worker_connections 1024; 
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=montmelo_cache:10m max_size=1g inactive=60m;

    upstream cluster_apache {
        server apache1:80;
        server apache2:80;
    }

    server {
        listen 80;
        location / {
            proxy_pass http://cluster_apache;
            proxy_cache montmelo_cache;
            proxy_cache_valid 200 10m;
            add_header X-Cache-Status $upstream_cache_status;
        }
    }
}
